IF(NOT OMPL_FOUND)
SET(OMPL_DIR "extern/ompl")
SET(OMPL_BUILD_DIR "${PROJECT_BINARY_DIR}/OMPL-${CMAKE_BUILD_TYPE}_build")
SET(OMPL_CONFIG_DIR "${OMPL_BUILD_DIR}/share/ompl/cmake")
SET(OMPL_CONFIG_FILE "${OMPL_CONFIG_DIR}/omplConfig.cmake")

IF(NOT EXISTS "${OMPL_CONFIG_FILE}")
    FILE(MAKE_DIRECTORY "${OMPL_BUILD_DIR}")

    EXECUTE_PROCESS(
            COMMAND ${CMAKE_COMMAND}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_INSTALL_PREFIX=${OMPL_BUILD_DIR}
            ${PROJECT_SOURCE_DIR}/${OMPL_DIR}
            WORKING_DIRECTORY ${OMPL_BUILD_DIR}
            RESULT_VARIABLE OMPL_CONFIGURE_RESULT
    )
    IF(NOT OMPL_CONFIGURE_RESULT EQUAL 0)
        MESSAGE(FATAL_ERROR "Failed to configure OMPL")
    ENDIF()

    EXECUTE_PROCESS(
            COMMAND ${CMAKE_COMMAND} --build . --parallel 32
            WORKING_DIRECTORY ${OMPL_BUILD_DIR}
            RESULT_VARIABLE OMPL_BUILD_RESULT
    )
    IF(NOT OMPL_BUILD_RESULT EQUAL 0)
        MESSAGE(FATAL_ERROR "Failed to build OMPL")
    ENDIF()

    EXECUTE_PROCESS(
            COMMAND ${CMAKE_COMMAND} --install .
            WORKING_DIRECTORY ${OMPL_BUILD_DIR}
            RESULT_VARIABLE OMPL_INSTALL_RESULT
    )
    IF(NOT OMPL_INSTALL_RESULT EQUAL 0)
        MESSAGE(FATAL_ERROR "Failed to install OMPL")
    ENDIF()
ENDIF()

MESSAGE(STATUS "OMPL build directory: ${OMPL_BUILD_DIR}")

FIND_PATH(
        OMPL_INCLUDE_DIR
        NAMES ompl/config.h
        NO_DEFAULT_PATH
        PATHS "${OMPL_BUILD_DIR}/include"
        PATH_SUFFIXES ompl-1.7 ompl-1.6
)

FIND_LIBRARY(
        OMPL_LIBRARY
        NAMES ompl
        NO_DEFAULT_PATH
        PATHS "${OMPL_BUILD_DIR}/lib"
)

SET(ompl_DIR "${OMPL_CONFIG_DIR}" CACHE PATH "Path to the OMPL package configuration" FORCE)
FIND_PACKAGE(ompl CONFIG QUIET NO_DEFAULT_PATH PATHS "${OMPL_CONFIG_DIR}")

IF(OMPL_FOUND)
    IF(NOT OMPL_INCLUDE_DIRS)
        SET(OMPL_INCLUDE_DIRS ${OMPL_INCLUDE_DIR})
    ENDIF()
    IF(NOT OMPL_LIBRARIES)
        SET(OMPL_LIBRARIES ${OMPL_LIBRARY})
    ENDIF()
    MESSAGE(STATUS "OMPL found @ ${OMPL_INCLUDE_DIRS}")
ELSEIF(OMPL_INCLUDE_DIR AND OMPL_LIBRARY)
    SET(OMPL_INCLUDE_DIRS ${OMPL_INCLUDE_DIR})
    SET(OMPL_LIBRARIES ${OMPL_LIBRARY})
    SET(OMPL_FOUND TRUE)
    MESSAGE(STATUS "OMPL found @ ${OMPL_INCLUDE_DIR}")
ELSE()
    MESSAGE(FATAL_ERROR "OMPL not found")
ENDIF()
MARK_AS_ADVANCED(OMPL_FOUND)
MARK_AS_ADVANCED(OMPL_INCLUDE_DIR OMPL_INCLUDE_DIRS)
MARK_AS_ADVANCED(OMPL_DIR)

ENDIF(NOT OMPL_FOUND)
